backend:
  name: github
  repo: tomhankcryp/ideko-site
  branch: main

media_folder: "assets/imgs/uploads"
public_folder: "/assets/imgs/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
